services:
  - type: web
    name: workforce-scheduling-system
    runtime: node
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm start --prefix backend
    healthCheckPath: /api/health
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
